# tasks file
---
- name: install | dependencies
  apt:
    name: "{{ grafana_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - grafana-install-dependencies

- name: install | additional
  apt:
    name: "{{ grafana_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - grafana-install-additional
