# tasks file for grafana
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ grafana_dependencies }}"
  tags:
    - grafana-install-dependencies

- name: install | additional
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ grafana_install }}"
  tags:
    - grafana-install-additional
