# tasks file
---
- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - grafana
    - grafana-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - grafana
    - grafana-install

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - grafana
    - grafana-configure

- name: start and enable service
  ansible.builtin.service:
    name: grafana-server
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - grafana-start-enable-service
