# tasks file
---
- include: repository.yml
  tags:
    - configuration
    - grafana
    - grafana-repository

- include: install.yml
  tags:
    - configuration
    - grafana
    - grafana-install

- include: configure.yml
  tags:
    - configuration
    - grafana
    - grafana-configure

- name: start and enable service
  service:
    name: grafana-server
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - grafana-start-enable-service
