# tasks file
---
- name: repository | dependencies
  ansible.builtin.apt:
    name: "{{ grafana_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - grafana-repository-dependencies

- name: create (keyrings) directory
  ansible.builtin.file:
    path: "{{ grafana_keyring_dst | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - grafana-repository-keyrings-directory-create

- name: download (keyring) file  # noqa command-instead-of-module risky-shell-pipe
  ansible.builtin.shell: >
    curl -sL {{ grafana_keyring_src }} | gpg --dearmor | tee {{ grafana_keyring_dst }}
  args:
    creates: "{{ grafana_keyring_dst }}"
  tags:
    - grafana-repository-keyring-file-download

- name: add (keyring) file  # noqa command-instead-of-module risky-shell-pipe
  ansible.builtin.shell: >
    apt-key add < {{ grafana_keyring_dst }}
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version is version('16', '<=')
  tags:
    - grafana-repository-keyring-file-download

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    mode: 0644
  with_items: "{{ grafana_repositories }}"
  tags:
    - grafana-repository-add
