# tasks file
---
- name: repository | dependencies
  apt:
    name: "{{ grafana_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - grafana-repository-dependencies

- name: repository | add public key
  apt_key:
    id: "{{ item.id }}"
    keyserver: "{{ item.keyserver }}"
    state: present
  with_items: "{{ grafana_apt_keys }}"
  tags:
    - grafana-repository-public-key

- name: repository | add
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    mode: 0644
  with_items: "{{ grafana_repositories }}"
  tags:
    - grafana-repository-add
